### ISSUE TITLE
HASURA_GRAPHQL_JWT_SECRET not working with RS256 in docker-compose

### ISSUE THREAD

**Issue by jakobrosenberg** [hasura/graphql-engine#1288]
From docker-compose.yaml
HASURA_GRAPHQL_JWT_SECRET : '{"type":"RS256", "key":"-----BEGIN PUBLIC KEY-----[mypublickey]-----END PUBLIC KEY-----"}'

``Fatal Error: JWT conf: Error in $: Invalid JWK: Could not decode PEM: invalid PEM delimiter found``

Am I doing something wrong?

**Comment by shahidhk** [comment]
@jakobrosenberg This is typically a quoting/newline error. Can you use https://hasura.io/jwt-config and generate the value with proper escaping etc. and try agian?

**Comment by shahidhk** [comment]
Yes, as mentioned [here](https://docs.hasura.io/1.0/graphql/manual/auth/jwt.html#key),

> 
> `key`
> 
> - In case of symmetric key (i.e. HMAC based key), the key as it is. (e.g. - “abcdef…”).
> - In case of asymmetric keys (RSA etc.), only the public key, in a PEM encoded string or as a X509 certificate.

**Comment by jakobrosenberg** [comment]
Thank you for your help @shahidhk .

For anyone else with this problem, my solution was to decode the public key to XML and then reencode it to PEM.
https://superdry.apphb.com/tools/online-rsa-key-converter

**Comment by mklueh** [comment]
I´m running into the same error with my Kubernetes deployment.yml.

According to the documentation we have two possibilities declaring a public key

> 1. In case of symmetric key (i.e. HMAC based key), the key as it is. (e.g. - “abcdef…”). The key must be long enough for the algorithm chosen, (e.g. for HS256 it must be at least 32 characters long).
> 2. In case of asymmetric keys (RSA etc.), only the public key, in a PEM encoded string or as a X509 certificate.

So as our key is RS256 I´ve set that as the type and attached the key within the Json.

```
      containers:
        - image: hasura/graphql-engine:v1.0.0-beta.9
          imagePullPolicy: IfNotPresent
          name: hasura
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://hasura:[MASKED]@192.168.22.11:5432/
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
              value: "startup, http-log, webhook-log, websocket-log, query-log"
            - name: HASURA_GRAPHQL_JWT_SECRET
              value: '{"type": "RS256","key": "TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFxOXBSeGY0TEtTcVErT1FGMDNXdVIrY21kRThYOFd1ZjVVQ3N1T1ZwNVlqM25vWFdZVnFhMUcrOTFhamJxUEVCZkEwWTljcW1CaWVJb0Z1UVdqZURlSnIvL0dJdjNnQXNtMEZQMzhleHgvMEFtMm1lQWhrdzltVVFaYUxOcStvSHZyUDdMUEIvOTNoNnBpUUVHak9rZXQyOEoyQW5pVDlpU2JadTNBZnNFNUdrN0hhZ2xZZWp3ZjlFTjRGdVM2UjVyU2lOeTRPemNBSExpbHVUVUMzQURSZjQ0alQ4end0UDdxOUk2aTB5aUVJeUR4Wlc4NHF6SGlyU1pWUEVqc0hheTNCNXpYK3NFdVhERythc1phMDdDWm1LL1Q0NGZoUWdhdnp3eG9ZMEw1N0RKYmtJUFk3WjFsUlJIL1E2UmlBS2FzQUR2THVRNzBRQzRzWEFRa2x3SlFJREFRQUI=","claims_namespace": "hasura","claims_format": "json"}'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
```

Producing:

> Fatal Error:- Environment variable HASURA_GRAPHQL_JWT_SECRET: Error in $: Invalid JWK: Could not decode PEM: No pem found No pem found

I´m not sure why it is expecting a PEM key anyway, although it seems to be an optionality.

However I´ve tried the same with our PEM key as well which leads to the same error.

It is unclear to me what´s the issue.

The solution of @jakobrosenberg  to convert it to XML and back to PEM with the converter provided is meaningless, as the result is the same in my case.

I would appreciate any help / clarification with this issue. Thanks in advance

**Comment by ecthiender** [comment]
@mklueh 

> `'{"type": "RS256","key": "TUlJQklqQU5CZ2txaGtp......"}`

The above key is not in a valid format. The docs mention, it has to be either in PEM format or x509 certificate format. See examples here: https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html#rsa-based

Let me know if this helps.

**Comment by mklueh** [comment]
@ecthiender 
I agree, the key above is not in the PEM format, however I´ve tried the same with our PEM formatted key from the .pem file

```
      containers:
        - image: hasura/graphql-engine:v1.0.0-beta.9
          imagePullPolicy: IfNotPresent
          name: hasura
          env:
            - name: HASURA_GRAPHQL_DATABASE_URL
              value: postgres://hasura:[MASKED]@192.168.22.11:5432/masterdata
            - name: HASURA_GRAPHQL_ENABLE_CONSOLE
              value: "true"
            - name: HASURA_GRAPHQL_ENABLED_LOG_TYPES
              value: "startup, http-log, webhook-log, websocket-log, query-log"
            - name: HASURA_GRAPHQL_JWT_SECRET
              value: '{"type": "RS256","key": "-----BEGIN PUBLIC KEY-----
                                               MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA7gtigpr8za0aY4pl5KVE
                                               93FPfwk9lfF9OX1QtMCP8fEm1aQL3SqNBlf+pRC2/TW0p5U5XcfFO/YLVMKzGpEG
                                               XD85SFyQbHUIoBswY6y4HswmeLA2/O+/Jo6guiPriXWpq4QS6arJgdCr+LGsphq3
                                               sY/Lxr8YOJWbCpM8UoR4foF580ixnfKSY41sHneTF9GwQyv1zt8uJ9MviBZpvCS1
                                               1wC7K81q0mPyM5QGBSdLDvTLizf4htOEQufRVzF7e4n2zFsnLXgmlyUFLRW/DOBV
                                               /lr1O7IO5WVRNf4M8x5pmtsG2dDJ9RBogx+s3cibkcwzPJuLd/Hru9CoCtMAEMnh
                                               7wIDAQAB
                                               -----END PUBLIC KEY-----","claims_namespace": "hasura","claims_format": "json"}'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
```

I´ve tried that with spaces, with no spaces, as a single line without line breaks etc and it always produces 

> Fatal Error: JWT conf: Error in $: Invalid JWK: Could not decode PEM: invalid PEM delimiter found

**Comment by denizkenan** [comment]
facing with this error again.  previously working config (generated via: https://hasura.io/jwt-config) is started causing the error. kinda stuck with what to do. any idea?


k8s env versions:
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-13T11:52:32Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by shahidhk** [comment]
@denizkenan Have you checked out the line delimiter?

**Comment by denizkenan** [comment]
@shahidhk : Thank you for the reply.
_Config not the cause of the problem.
It still works flawlessly if Hasura is launched using docker-compose.
It used to work with our Kubernetes cluster as well._ 

**So far:**
-Used to work with same config, hasura version, kubetctl version
-Stopped working with k8s v1.14.6 AKS (Azure Kubernets Service).
-Not working still with different kubectl version, hasura version, different platform(macosx, linux) against same k8s cluster 

**Possible cause:**
We suspect that Kubernetes version in question does not like the way it is suggested to use jwt config.


We will change k8s version and try again. if it fails,
We will try with different methods(yaml format, load from configmap, load from secrets etc..).

**Comment by denizkenan** [comment]
Ok,  problem was related with our tooling.
`$(echo sed ...)` was replacing new line character with a weird character(that looks like a space character).  changed the way sed is used(avoiding any `echo sed`) and problem is solved.

**Comment by coltonbh** [comment]
Also, if trying to use the jwk_url with Auth0 it will not work (currently) as noted in the know issues here: https://docs.hasura.io/1.0/graphql/manual/auth/authentication/jwt.html#auth0

**Comment by batadamnjanovic** [comment]
After a lot of time of trying with HASURA_GRAPHQL_JWT_SECRET to work in docker-compose.yaml, my solution was to add a line break after END PUBLIC KEY-----\n 

Example:
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAq9dr+td6cuvIBWT/wKJf\nk2FqFv7bMMByYXEV/OyweTNA8gT2ClxPhxD2gF1qzZpQK+sHaRLAv2QH6R59cTt3\nJwL9YOY/Y79z3H3XGGmx6BuWp2wHS6RzukeCogSFF9RAWOPhwtiGtjVHOabnSH4U\nqNFb2aZJR5BJuHCfqcMfNtSlM9K8QHrgS1nXJqYooa0pCt9PO+xjaNRszwBzB0c6\nwbiuuhpFl/tLiwIQch7AniPQZGvHQ3tObIL1JKL3WQwtBVsw9k/Amk3OdYynpVSh\nEH/8twzdE61H5aDHCFwaQ7kLbE8SrFzRjvrpFcFSgKW7cRvNyUn+VgIRQzngQlha\nMQIDAQAB\n-----END PUBLIC KEY-----\n", "claims_format": "json"}'

**Comment by noahwaldner** [comment]
I'm also struggling with this issue and 'v already tried all the showed solutions.

has anyone used another way to get this working?

**Comment by nuevoleonkx** [comment]
I tried to create my public/private keys with gpg and ssh-keygen but still not working,,,
I ran the following commands to create the keys

`gpg --full-gen-key` choose 2048 (rs256) and complete the creation process

then export the public key
```
gpg -a --export KEYID > mykey.asc.txt
```

and export the private key
```
gpg -a --export-secret-keys KEYID > mykey.secret.asc.txt
```

take the generated public key but getting the same errors above
Fatal Error:- Environment variable HASURA_GRAPHQL_JWT_SECRET: Error in $: Invalid JWK: Could not decode PEM: invalid PEM: decoding failed: base64: input: invalid length invalid PEM: decoding failed: base64: input: invalid length

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBGC5KUgBCACi/MC2XSID+1gfammVpWskh6CK3F7nOiH9uD8vnM28Bvge/0yS
Vptqg41asD3ZuLCwDD0v+QvSeYwv1XpG4EEDhG/vjpEEYe32/AeG4ef0HuYWHL2w
CiqWmUI7LpfBRqgYz2WpQkGoLf/iFZiDduvyoAppu1jT3Ssh1fLqS3Q9hlhJTm2N
4XHMSmxot7A6Ec/w0jl2xn8n7pTweSY47zV1WOTJiNa9hxuXyoSmhH30vg3U1sPa
beiMIb3NHDPb4MWZs2GjOZ5v0blBonYXJGWIeKb7hvijyudfo9kWd+94ftmMQcT0
C6KLYkO11yKSqGYQsjE1aN3JtmW17qeg3Cu1ABEBAAG0IGxlb25lbCAoMjU2KSA8
bGVvbmVsQGRhdHlyYS5jb20+iQFOBBMBCgA4FiEEkIOxJYkFhH0cZvo26jIoR8kS
yVcFAmC5KUgCGwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQ6jIoR8kSyVdu
+Qf+LO857MtlO6UrQNb7OzG5847onCEbfarfjYiEqPMiBzy1L1ZXb9cCDX2crPbA
U/O8ETTXXs4piqgYeZf9Men48zwZiT8bcoO6BHo0fAmG38+PDqqDS0vQqjItXmK0
C9xb8UEIm2A4NwaFon1uhNuarY42cSvHDCR2kbJPx/RQ/M2PCOi+8/2qlHfbLy52
11iGdlyxnV2ZuwXAuYNZnOJTzGlMIW8gETTevixbnHmga4gSGfA/gHnWtR7vhMDb
ALgibvaStmmwBLXrpsZ/gaTp3Xvf7/9SMGRVfU7O+rDrx2kVUdbhuvCohvFpz+wf
e4bPaJSu+7MFp3JfGIsNUdLt0bkBDQRguSlIAQgAuDLrEWfk3fWEPJU2s3ECJauE
eoTVIiakVHh136QnKMPNrb/NJ8xHaTJjTb69tnI1re7TNmK1aqndde2IgpUArOvw
OU+k3pY6Bifv98KBRfMY1kUBgJbMtGEnQlvN/9me4UBs746ZuCxihKoXqa0UlJR9
/YkD8ApC+DiSwxJcdKkjL4EPo+61LTupDGnkAgm8VbrPzGSYfdu3Y4r/XVRHaiJu
TuJFkZyx8YBcZzvGOptqRxcATm+WK3wtJSBrJUgBUXJ8S/Gi+R/WmvZopzAkRAtK
rvahs8NW2a66gs3r4F8bxam1YgF6p3PE0b/1wtAVAmNwwSFozJg5cfQ2btPtWQAR
AQABiQE2BBgBCgAgFiEEkIOxJYkFhH0cZvo26jIoR8kSyVcFAmC5KUgCGwwACgkQ
6jIoR8kSyVdQiggAmv5HtqkrcAapkNUHjMbYMM8pz+DN0EfT/WTV65epdvBzypa6
/SY/gvJ28vzpBTMH2LvveW74H+sIu66PoMSM/t+lsQAOh0OlhtT+FiyjcxmwXJXu
QITzuh/pVHATV8IgFja3gHMr4Wz0Xs7S6WcTArwNSunFbm6K8X75h0w2O705dIlA
QWtqmtrCTtGO9a9hsuMmD5ICKUWyGMdRuR18o9hYLnMgTtcJcDKfmk7o/bOOp6Fc
slm92Rcpk7GktNy34xkcSClJVNiKgqG2OF2d36vCjxhfQXwZXln7HRF/Sp1CNBpY
DByYRcKOiKRh05ek/2oWGyzDRHlG6FAp/+hKKw==
=z7ow
-----END PGP PUBLIC KEY BLOCK-----

y tried several times and getting the same result

{"type":"RS256", "key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\nmQENBGC5KUgBCACi/MC2XSID+1gfammVpWskh6CK3F7nOiH9uD8vnM28Bvge/0yS\nVptqg41asD3ZuLCwDD0v+QvSeYwv1XpG4EEDhG/vjpEEYe32/AeG4ef0HuYWHL2w\nCiqWmUI7LpfBRqgYz2WpQkGoLf/iFZiDduvyoAppu1jT3Ssh1fLqS3Q9hlhJTm2N\n4XHMSmxot7A6Ec/w0jl2xn8n7pTweSY47zV1WOTJiNa9hxuXyoSmhH30vg3U1sPa\nbeiMIb3NHDPb4MWZs2GjOZ5v0blBonYXJGWIeKb7hvijyudfo9kWd+94ftmMQcT0\nC6KLYkO11yKSqGYQsjE1aN3JtmW17qeg3Cu1ABEBAAG0IGxlb25lbCAoMjU2KSA8\nbGVvbmVsQGRhdHlyYS5jb20+iQFOBBMBCgA4FiEEkIOxJYkFhH0cZvo26jIoR8kS\nyVcFAmC5KUgCGwMFCwkIBwIGFQoJCAsCBBYCAwECHgECF4AACgkQ6jIoR8kSyVdu\n+Qf+LO857MtlO6UrQNb7OzG5847onCEbfarfjYiEqPMiBzy1L1ZXb9cCDX2crPbA\nU/O8ETTXXs4piqgYeZf9Men48zwZiT8bcoO6BHo0fAmG38+PDqqDS0vQqjItXmK0\nC9xb8UEIm2A4NwaFon1uhNuarY42cSvHDCR2kbJPx/RQ/M2PCOi+8/2qlHfbLy52\n11iGdlyxnV2ZuwXAuYNZnOJTzGlMIW8gETTevixbnHmga4gSGfA/gHnWtR7vhMDb\nALgibvaStmmwBLXrpsZ/gaTp3Xvf7/9SMGRVfU7O+rDrx2kVUdbhuvCohvFpz+wf\ne4bPaJSu+7MFp3JfGIsNUdLt0bkBDQRguSlIAQgAuDLrEWfk3fWEPJU2s3ECJauE\neoTVIiakVHh136QnKMPNrb/NJ8xHaTJjTb69tnI1re7TNmK1aqndde2IgpUArOvw\nOU+k3pY6Bifv98KBRfMY1kUBgJbMtGEnQlvN/9me4UBs746ZuCxihKoXqa0UlJR9\n/YkD8ApC+DiSwxJcdKkjL4EPo+61LTupDGnkAgm8VbrPzGSYfdu3Y4r/XVRHaiJu\nTuJFkZyx8YBcZzvGOptqRxcATm+WK3wtJSBrJUgBUXJ8S/Gi+R/WmvZopzAkRAtK\nrvahs8NW2a66gs3r4F8bxam1YgF6p3PE0b/1wtAVAmNwwSFozJg5cfQ2btPtWQAR\nAQABiQE2BBgBCgAgFiEEkIOxJYkFhH0cZvo26jIoR8kSyVcFAmC5KUgCGwwACgkQ\n6jIoR8kSyVdQiggAmv5HtqkrcAapkNUHjMbYMM8pz+DN0EfT/WTV65epdvBzypa6\n/SY/gvJ28vzpBTMH2LvveW74H+sIu66PoMSM/t+lsQAOh0OlhtT+FiyjcxmwXJXu\nQITzuh/pVHATV8IgFja3gHMr4Wz0Xs7S6WcTArwNSunFbm6K8X75h0w2O705dIlA\nQWtqmtrCTtGO9a9hsuMmD5ICKUWyGMdRuR18o9hYLnMgTtcJcDKfmk7o/bOOp6Fc\nslm92Rcpk7GktNy34xkcSClJVNiKgqG2OF2d36vCjxhfQXwZXln7HRF/Sp1CNBpY\nDByYRcKOiKRh05ek/2oWGyzDRHlG6FAp/+hKKw==\n=z7ow\n-----END PGP PUBLIC KEY BLOCK-----\n"}


Is there something I'm missing?
TIA

**Comment by Lexe003** [comment]
Experiencing the same

**Comment by ash0080** [comment]
1. use a text edit or IDE, 
2. "find and replace" all line breaks with "\n"
3. paste into the yaml or use a .env file

**Comment by comerc** [comment]
Added HASURA_GRAPHQL_ADMIN_SECRET for local docker-compose work fine with firebase HASURA_GRAPHQL_JWT_SECRET: '{"type":"RS256","jwk_url": "https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com", "audience": "my-project-id", "issuer": "https://securetoken.google.com/my-project-id"}'

**Comment by mullermad** [comment]
For Hasura to properly validate JWTs with an HS256 symmetric key, you need to use a key that is at least 32 characters long. Here’s how you can structure the HASURA_GRAPHQL_JWT_SECRET for HS256 in your Docker Compose file, ensuring the key meets the required length:

**Comment by Zerebokep** [comment]
No idea what interferes here, but putting the HASURA_GRAPHQL_JWT_SECRET env directly after HASURA_GRAPHQL_ADMIN_SECRET fixed it for me.
