### ISSUE TITLE
Missing hdb_view in 1.1.0-beta.1?

### ISSUE THREAD

**Issue by nirvdrum** [hasura/graphql-engine#3710]
I tried out 1.1.0-beta.1 today and I've been unable to run my app with it. Using a Docker Compose environment that upgraded from 1.0.0 to 1.1.0-beta.1, I'm getting an error when trying to insert data:

```
ERROR:  relation "hdb_views.eca2225ad9f81f9075915f94e6c65a4f91c855f7e0bdb795d09fee54" does not exist at character 47
```

Thinking that my DB somehow got corrupted, I tore down my Docker Compose environment and removed the persistent volume. With a clean install, I'm unable to run my migrations:

```
[42883] FatalError: function hdb_views.dbb780ae7437f2a5faf3926515a7a206f5bc9b227ba22a748b9f4587() does not exist
```

I wish I had more details about what's going on there. Unfortunately, that's a Hasura managed table that I know very little about. If I go back to 1.0.0, my migrations apply fine and I'm able to insert data successfully.

**Comment by lexi-lambda** [comment]
Urk—this is my fault. This issue was already reported before we made the beta release in https://github.com/hasura/graphql-engine/issues/3354#issuecomment-569736691, but at the time I didn’t worry much about it because I knew we were getting rid of those views anyway in #3598. However, I’ve now realized that change didn’t make it into this release, so the issue is a real issue, after all!

This will definitely be fixed by #3598. I think it’s unlikely to be worth trying to patch independently of that change, since it should be merged very soon anyway. In the meantime, I’d recommend just staying on 1.0.0 if you’ve bumped into it.

(An aside: we should really not be notifying everyone to upgrade to `1.0.0-beta.1`, since it’s a *beta*, and we have stable releases now. That’s a holdover from pre-1.0.0 that we forgot about, and we’ll fix that soon.)

**Comment by MarcelloTheArcane** [comment]
@lexi-lambda I'm still getting this error when I downgrade back to 1.0.0. Is there anything I can do to sort this out?

**Comment by lukaspili** [comment]
Are there specific instructions to downgrade to 1.0.0? 
Setting the version of `hdb_catalog.hdb_version` to 28 does not seem to be enough. Hasura is crashing on startup with:

```
failed to build schema-cache because of inconsistent metadata
```

**Comment by nirvdrum** [comment]
In my case, I was only trying it out on a local installation, so I just blew everything away and started from scratch. I lost some test data, but nothing critical.

**Comment by nyamba** [comment]
we have same issue, how to solve it? or downgrade guide?

**Comment by shahidhk** [comment]
To downgrade from `v1.1.0-beta.1` to `v1.0.0`:
- Stop hasura
- Execute this SQL on your database: https://github.com/hasura/graphql-engine/blob/db5072dff3efdd3560c9755104550c698e5cd719/server/src-rsr/migrations/29_to_28.sql
- Start hasura 1.0

**Comment by shahidhk** [comment]
fixed in https://github.com/hasura/graphql-engine/commit/9ed8f717a76c427d69efdc8fa55396356d9034be
