### ISSUE TITLE
Can't install cli-ext due to checksum mismatch

### ISSUE THREAD

**Issue by va3093** [hasura/graphql-engine#6177]
Hey I am unable to install the `cli-ext` pluging.

Getting this error:

```
FATA[0001] failed to install plugin "cli-ext": install failed: failed to unpack into staging dir: failed to unpack the plugin archive: checksum does not match, want: acdfd6d9a0fc2a7c10f47e6be2d48d1db02287cc456162b992e287d181d75447, got 0019dfc4b32d63c1392aa264aed2253c1e0c2fb09216f8e2cc269bbfb8bb49b5 ```

**Comment by scriptonist** [comment]
@va3093 Thanks for bringing this to notice, this should be fixed now, can you please help us verify

**Comment by va3093** [comment]
🚀 . Thanks works now.

**Comment by peterldowns** [comment]
What was the underlying problem and fix?

**Comment by scriptonist** [comment]
@peterldowns We had a failed release which intermittently pushed a different version of binary to the cloud bucket which we later rolled back.

**Comment by limenutt** [comment]
I'm still having this issue on hasura-cli 1.3.3. Do I have to upgrade to the 1.3.4 beta?

**Comment by scriptonist** [comment]
@limenutt might be https://github.com/hasura/graphql-engine/issues/6219

**Comment by limenutt** [comment]
Yes, `rm -rf ~/.hasura` did the trick, thank you, @scriptonist !
