### ISSUE TITLE
Metadata is Out-of-Date

### ISSUE THREAD

**Issue by sashker** [hasura/graphql-engine#6805]
## Problem
When I'm trying to create tables or events on the console in a local docker-compose installation I always get the error in the warning pop-up:

`Metadata is Out-of-Date
The operation failed as the metadata on the server is newer than what is currently loaded on the console. The metadata has to be re-fetched to continue editing it.

Do you want fetch the latest metadata?`

### Installation
Fresh
docker-compose
PostgreSQL 13
v2.0.0-alpha.9.cli-migrations-v3

### Docker log:

`graphql-engine_1  | {"type":"http-log","timestamp":"2021-04-21T09:05:13.322+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"admin"},"error":{"path":"$","error":"metadata resource version referenced (8) did not match current version","code":"conflict"},"request_id":"834f599c-d3d7-4d5b-83aa-c3782b6ca3c6","response_size":111,"query":{"resource_version":8,"args":[{"args":{"configuration":{"custom_root_fields":{},"custom_column_names":{}},"table":{"schema":"public","name":"my_accounts"}},"version":1,"type":"pg_track_table"}],"version":1,"type":"bulk"}},"request_id":"834f599c-d3d7-4d5b-83aa-c3782b6ca3c6","http_info":{"status":409,"http_version":"HTTP/1.1","url":"/v1/metadata","ip":"172.23.0.1","method":"POST","content_encoding":null}}}
graphql-engine_1  | {"type":"schema-sync-thread","timestamp":"2021-04-21T09:05:13.322+0000","level":"info","detail":{"thread_type":"processor","info":{"message":"Schema Version changed with no notifications"}}}`

**Comment by tirumaraiselvan** [comment]
Will be fixed in next release.

**Comment by 0x777** [comment]
@tirumaraiselvan Is this already fixed? Can you point me to the PR/commit?

**Comment by tirumaraiselvan** [comment]
@0x777 Here: https://github.com/hasura/graphql-engine-mono/pull/1163

**Comment by 0x777** [comment]
@sashker The fix is landed on master and will be part of the next release. Closing this for now but feel free to reopen if you see this again.

**Comment by bkniffler** [comment]
I'm using 2.0.1. and see the same error while trying to add tables to my database through hasura dashboard. Is this a regression?

**Comment by Rafat97** [comment]
I am facing same issues. 

![image](https://user-images.githubusercontent.com/21246862/126027660-8883df04-44cd-42e1-bc0d-3b17d2bac079.png)
 
I am using docker -

**Comment by Motoxpro** [comment]
I am getting the same as @Rafat97. Reproducibility on my end is also the same.

**Comment by crates** [comment]
@tirumaraiselvan / @martin-hasura ~
I'm having this same problem with Hasura v2.0.3 - it's definitely NOT fixed yet.
Please advise when you think this might be corrected long-term. Thank you!

**Comment by KloudJack** [comment]
@tirumaraiselvan I believe this issue is the underlying cause: #7324

It seems to be tied to the resource_version functionality introduced with 2.0.
